{% set name = "tangram_nciplot" %}
{% set version = environ.get('GIT_DESCRIBE_TAG', 'v')[1:] %}
package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: ../
  git_tag: v{{version}}

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', '0')|int }}
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
  run:
    - python
    - pychimera     >=0.2.6
    - libtangram
    - nciplot
    - cunci         # [linux]

about:
  home: http://github.com/insilichem/tangram_nciplot
  license: MIT
  license_family: MIT

  summary: 'UCSF Chimera extension to run and visualize NCIPlot calculations'

  description: |
    UCSF Chimera extension to run and visualize NCIPlot calculations.
    NCIPLOT enables graphical visualization of NCI (non covalent interactions)
    in molecules.
  doc_url: http://tangram-suite.readthedocs.io/en/latest/tangram_nciplot.html
  dev_url: https://github.com/insilichem/tangram_nciplot


